version: '3'
services:
    app:
        container_name: docker-osoc
        restart: always
        image: cultura:latest
        ports:
            - "3000:3000"
        depends_on: 
            - mongo
        volumes:
            - .:/src/app
    mongo:
        container_name: mongo
        image: mongo
        expose: 
            - "27017"
        ports:
            - "27017:27017"